### ISSUE TITLE
Parser error

### ISSUE THREAD

**Issue by Wang4758** [nickovic/rtamt#48]
Hi there,

I got Syntax Error for specification "c = always((a>=3) and eventually(b>4) -> (b>=3))". It would work if I add a time boundary for the `eventually` operator. Since I couldn't find any documentation about the syntax that is allowed by `rtamt`, could you please help me understand this error? Thanks in advance.

**Comment by nickovic** [comment]
Because we aim at having an online monitoring library, we allow only the so-called bounded fragment of STL, meaning that only the top-level operator (always) can be unbounded, but all the other operators must be time bounded (eventually must be replaced by eventually[a:b]).

I am documenting it, and the documentation explaining the syntax and semantics will be available this week.

**Comment by Wang4758** [comment]
> Because we aim at having an online monitoring library, we allow only the so-called bounded fragment of STL, meaning that only the top-level operator (always) can be unbounded, but all the other operators must be time bounded (eventually must be replaced by eventually[a:b]).
> 
> I am documenting it, and the documentation explaining the syntax and semantics will be available this week.

Understood, thanks!

**Comment by nickovic** [comment]
The semantics of STL that we use in the library is now documented in README.md (consolidation branch).

**Comment by nickovic** [comment]
Comments welcome.
