### ISSUE TITLE
Possible bug with eventually?

### ISSUE THREAD

**Issue by Agnishom** [nickovic/rtamt#66]
Consider the following example execution:

```python
>>> import rtamt
>>> spec = rtamt.STLDenseTimeSpecification()
>>> spec.name = 'Example'
>>> spec.declare_var('x','float')
>>> spec.declare_var('out', 'float')
>>> spec.spec = 'out = eventually[2,2](x >= 0)'
>>> spec.parse()
>>> spec.pastify()
>>> spec.update(['x',[[0,0]]])
[]
>>> spec.update(['x',[[1,0]]])
[[0, 0.0]]
>>> spec.update(['x',[[2,1]]])
[[1, 0.0]]
>>> spec.update(['x',[[4,1]]])
[[2, 1.0]]
```

If I understand correctly, this represents a trace which has value 0 from 0 to 2, value 1 from 2 to 4. At time 1, I believe that the robustness of `eventually[2,2](x >= 0)` should be the robustness of `(x >= 0)` at time 3, which is supposed to be `2`. But the program reports a different value.

Maybe this is a bug? Or maybe I understand the semantics wrong?

**Comment by nickovic** [comment]
The formula phi = eventually[2,2](x>=0) is translated into the equisatisfiable past formula psi = once[2,2](x>=0) such that
rho(w,phi,t) = rho(w,psi,t+2).

Hence, while rho(w,phi,1) = 1, it is not the case for rho(w, psi, 1). Actually, the value of rho(w,psi,1) equals to 0 by default, but the output of the monitor in the interval [0, 2) shall be in a way discarded, since these values are not related to the satisfaction of the original formula phi.

**Comment by nickovic** [comment]
The pastification seems to bring confusion to several users. Onwe alternative way would be to return robustness of the original formula with the delay (this would be a trivial step, where we would just retract the pastification horizon from each output step). 

If anyone feels that this approach is worth discussion, please open a new thread.

**Comment by Agnishom** [comment]
So, to clarify, when the program says

```
>>> spec.update(['x',[[2,1]]])
[[1, 0.0]]
```

It is only saying that rho(w, psi, 1) = 0.0. Is this the correct way to understand the semantics?

**Comment by nickovic** [comment]
Yes, that is correct
