### ISSUE TITLE
One specification of the example is wrong

### ISSUE THREAD

**Issue by smallzjuer** [nickovic/rtamt#67]
Hi, I tried to run all the examples under this title:
https://github.com/nickovic/rtamt#example-usage
But for this code (https://github.com/nickovic/rtamt#dense-time-offline-monitor), it's unable to run it successfully.
It seems that all the 'always' and 'eventually' have to be followed by [x:y], or the code will crash.
I'll appreciate it if you can answer my question and fix the problem.
Thanks!

**Comment by smallzjuer** [comment]
I installed the tool from the master branch and tried to run the example given in 
https://github.com/nickovic/rtamt#dense-time-offline-monitor 
on Ubuntu 20.4. However, it reported an error: "". It seems the current version can only deal with the always and eventually operators followed by time duration  [a:b]. Could you please advise whether I can apply the always and eventually operators  directly without time duration?

**Comment by nickovic** [comment]
Thanks for your message, there are indeed two faults:
- the example pastifies the formula, which it should not do since we are doing the offline evaluation of the formula
- the bounded eventually is not implemented for offline monitors

The first issue is trivial to fix, for the second issue I will need a couple of days to add the functionality.

**Comment by nickovic** [comment]
The two issues are fixed.
